processing:
  discrete:
    handle_unknown: "ignore"
    fillna_value: 0

  continuous:
    scaler: "standard"       # standard, minmax, robust
    fillna_strategy: "mean"  # mean, median, zero

  discrete_sequence:
    max_sequence_length: 50
    padding_value: 0

  continuous_sequence:
    max_sequence_length: 50
    padding_value: 0.
